### ISSUE TITLE
Issue with Buffer Changes. 

### ISSUE THREAD

**Issue by tomblevins** [parnic/node-screenlogic#19]
Hey Parnic! Hope you are well. 
I saw that you added SLEquipmentConfigurationMessage and so I cloned down the latest to my test server to see if I can help make heads or tails of the arrays. That said... I also picked up, of course, the buffer changes you made a few weeks ago. 

I am getting some errors that the functions aren't declared. I tried to follow through your code to see if I could find them but I am just not that familiar with it yet. This is what I am seeing...

/usr/lib/node_modules/node-screenlogic/messages/SLGetGatewayDataMessage.js:11
      size = buf.readInt32LE(4) + 8;
                 ^

TypeError: buf.readInt32LE is not a function
    at new SLGetGatewayDataMessage (/usr/lib/node_modules/node-screenlogic/messages/SLGetGatewayDataMessage.js:11:18)
    at RemoteLogin.onConnected (/usr/lib/node_modules/node-screenlogic/index.js:87:23)
    at Socket.<anonymous> (/usr/lib/node_modules/node-screenlogic/index.js:80:13)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:215:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1115:10)

**Comment by parnic** [comment]
Thanks. I neglected to test remote logins before pushing those changes.
